### ISSUE TITLE
Non paired-end FASTQ files

### ISSUE THREAD

**Issue by mvheetve** [Pasquali-lab/UMI4Cats#1]
Hi,

I've been trying to use UMI4Cats but I keep getting this message when I use 'contactsUMI4C'

`Error in prepUMI4C(fastq_dir = fastq_dir, wk_dir = wk_dir, file_pattern = file_pattern,  : 
  Non paired-end FASTQ files with the extension _RX.fastq, _RX.fq, _RX.fq.gz
                                        or _RX.fastq.gz inVolumes/MVH_Linux/UMI-4C/ABCA4/fastq`

Tried several files, files from different runs... files look like this:
`@A00785:56:HHLLTDRXX:1:2101:1832:1000 1:N:0:ATCACG
NTTTGTCCTCGGCAAGAGCAATGTTTCTATCTTAGATAAACAGTACTCCTGGCAGAGGTAATAGCCTGAAGTGGGAATAAGCCTGGCTTATTCCAGAAACAGCAAGTAGCCCAATGTGGCTGGAGCAGAGTCAGGGAAGGGTGAAATAGT
+
#F,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFF:FFFF:FFF,FFFFFFFF`
and 
`@A00785:56:HHLLTDRXX:1:2101:1832:1000 2:N:0:ATCACG
CTTATAGTGATCAGAAGAGCTTATTTGTCCTGTCCCTTTCAACATCCAAGTTTTCTCTCTTACCTCCTCTTCTACTATTTCACCCTTCCCTGACTCTGCTCCAGCCACATTGGGCTACTTGCTGTTTCTGGAATAAGCCAGGCTTATTCCC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFFF,FF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFF`

paired files have the exact same name (except for R1 and R2). The test data provided with the installation worked fine. 

Any help would be appreciated
Mattias

**Comment by mireia-bioinfo** [comment]
Hello Mattias,

First of all, thank you for using UMI4Cats!

The error you are getting when running `contactsUMI4C` has more to do with the naming of the fastq files (or the path) rather than with the actual content of the files. To understand the cause of this error we would need: 

- Some examples on the naming of your fastq files, in case that might be an issue.
- The values of the arguments you are passing to `contactsUMI4C`, or at least the ones that are relevant to this error, which are: `fastq_dir` and `file_pattern`.

In the mean time,you can check the following, to see if that might be the cause for the error you are getting: 

- `fastq_dir` is set to the directory that contains all your fastq files (I assume from your error message that this should be `inVolumes/MVH_Linux/UMI-4C/ABCA4/fastq`).
- `file_pattern` contains an actual pattern that is present in your file names. This argument will filter your files according to their names, so if the pattern is not present it will return the error you posted here. If you don't want to use this argument just don't include it in your function call, as it is `NULL` by default.
- Check the fastq files in `fastq_dir` follow the naming conventions prompted by the error.

**Comment by mvheetve** [comment]
Hi Mireia,

thank you for your swift answer, unfortunately I got busy with other work. I plan on diving into UMI4Cats again next week. 
You were right, I had an underscore too many in my path, but I didn't look for it since I interpreted 
` Non paired-end FASTQ files` as "The files you provided are not paired-end', while you clearly mean "can't find paired-end files". My bad :)

Anyway, let's see how I do next week and maybe I'll get back to you with more questions. 

Regards
Mattias
