### ISSUE TITLE
Apply to reads with unequal read length

### ISSUE THREAD

**Issue by YuanlongLiu** [Pasquali-lab/UMI4Cats#7]
Hi, just another comment, there can be situations when the read lengths in fastq are not unique. For example, after adaptor trimming. In the package there are multiple places where the "unique" function has been used to collect information from different reads, should be an issue.

**Comment by msubirana** [comment]
Hi YuanlongLiu,

UMI4Cats is designed for unique fastq reads. It is not necessary trimming the reads due to there are a strict QC process where reads that not present an adequate quality are filtered out.

The "unique" function is necessary for the collapsing of PCR duplicates and for the correct generation of the UMIs.

**Comment by YuanlongLiu** [comment]
Hi I mean these ones:

R/statsUMI4C.R: 

## here unique(ShortRead::width(reads_fqR1)) will choose some arbitary number if ShortRead::width(reads_fqR1) is not unique
if (nchar(as.character(barcode)) > unique(ShortRead::width(reads_fqR1))) {
                barcode <- substr(barcode, 1, unique(width(reads_fqR1)))


R/demultiplexFastq.R:

## the same here:
if (nchar(as.character(barcode)) > unique(ShortRead::width(reads_fqR1))) {
    barcode <- substr(barcode, 1, unique(width(reads_fqR1)))

R/contactsUMI4C.R:

## the same here
gaps <- IRanges::gaps(matches,
            start = 1,
            end = unique(nchar(as.character(prep_dna_string)))
   )
